echo "name: Deploy Backend ZIMA

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run tests  # COMENTADO TEMPORALMENTE
      #   run: pytest tests/

      - name: Deploy to Railway
        env:
          RAILWAY_API_TOKEN: \${{ secrets.RAILWAY_API_TOKEN }}
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          railway up --service backend-zima
" > .github/workflows/deploy.yml
